### ISSUE TITLE
Problem selecting font (wx3270-1.2beta3-noinstall64, Win11)

### ISSUE THREAD

**Issue by tatzio** [pmattes/Wx3270-New#19] opened 2024-03-22 07:48 UTC
I really like the https://github.com/IBM/plex font family (Mono) on wx3270.
I've installed: 
[IBMPlexMono-Regular.ttf](https://github.com/IBM/plex/blob/master/IBM-Plex-Mono/fonts/complete/ttf/IBMPlexMono-Regular.ttf)
and 
[IBMPlexMono-Text.ttf](https://github.com/IBM/plex/blob/master/IBM-Plex-Mono/fonts/complete/ttf/IBMPlexMono-Text.ttf)
both very similar, `Text` is tiny bit bolder and I like it better.

Selecting `Regular` is no problem, but when I'm trying to switch to `Text` then `Text` + `Bold` is picked:
```
  "Font": {
    "Name": "IBM Plex Mono Text",
    "EmSize": 12.0,
    "Style": "Bold" <----
  }
```
when I modify *.wx3270 by hand to:
```
  "Font": {
    "Name": "IBM Plex Mono Text",
    "EmSize": 12.0,
    "Style": "Regular" <----
  }
```
font is selected properly.

It seems to me that the dialog used to select the font does not handle it properly for some reason.
I've tried both fonts on Office Word and Notepadd++ and both programs switch between both fonts without problems.

**Comment by pmattes** [comment] 2024-03-22 20:41
This is very strange. I am using a standard .NET FontDialog object to do the font selection. When I test here and select IBM Plex Mono Text in the FontDialog (and I don't select Bold), the Font returned by the FontDialog has its Bold property set to true, and its Style property set to Bold. So that gives every indication that the selected font really is Bold.

I will keep digging, but so far I am stumped.

**Comment by tatzio** [comment] 2024-03-23 07:47
[This](https://developercommunity.visualstudio.com/t/font-selector-in-windows-forms-designer-does-not-f/565335) seems to be the same issue. Maybe there is a reason why programs usually use custom font selection mechanism? 
I do not know anything regarding font dev - but it seems there is some flexibility for how `Fontface` / `Style` is defined and this FontDialog does not handle well all cases?

**Comment by pmattes** [comment] 2024-03-23 21:52
I don't know a whole lot more about font development either. ;-(

It appears to be an issue with FontDialog, the .NET wrapper around the Win32 ChooseFont() function. I have code in the wc3270 Session Wizard that uses ChooseFont() directly, and it has no issues with this font. My guess is that the problem is with IBM Plex Mono Text having a weight of 450, which is between the convention for Regular (400) and Medium (450).

I will see if I can use ChooseFont directly with wx3270.

**Comment by tatzio** [comment] 2024-03-25 08:54
It would be great to fit whole font selection mechanics on Settings->Font tab.
Seems that most programs deal with that using very few controls (below Notepad++):
![image](https://github.com/pmattes/Wx3270-New/assets/106803609/5c966cd5-e3d4-422c-8c65-240858c5ba71)

**Comment by pmattes** [comment] 2024-03-25 13:08
Yes, I am doing just that already. I’m removing the Font tab altogether and replacing it with a group box on the Options tab. Almost done.

**Comment by pmattes** [comment] 2024-03-26 02:59
I've just committed the change to 1.2 and master. I left the Font tab there, but I replaced the 'Change' button with two combo boxes (family and size) and two buttons (bold and italic).

**Closed by pmattes** 2024-03-26 02:59 UTC
